/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConversationView {
  'id' : string,
  'messages' : Array<MessageView>,
  'user1' : Principal,
  'user2' : Principal,
}
export type ExternalBlob = Uint8Array;
export interface FullUserProfile {
  'bio' : string,
  'displayName' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'email' : string,
  'phone' : string,
  'location' : string,
}
export interface MessageView {
  'text' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'readBy' : Array<Principal>,
}
export interface Pet {
  'id' : string,
  'age' : string,
  'photoBlobs' : Array<ExternalBlob>,
  'ownerId' : Principal,
  'name' : string,
  'size' : string,
  'tags' : Array<string>,
  'description' : string,
  'healthStatus' : string,
  'breed' : string,
  'species' : string,
  'location' : string,
  'isAdopted' : boolean,
}
export interface PublicUserProfile {
  'bio' : string,
  'displayName' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'location' : string,
}
export interface Stats {
  'totalPets' : bigint,
  'totalMessages' : bigint,
  'adoptedPets' : bigint,
  'totalUsers' : bigint,
  'totalConversations' : bigint,
}
export type Time = bigint;
export type UserProfileResult = { 'publicView' : PublicUserProfile } |
  { 'full' : FullUserProfile };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminBanUser' : ActorMethod<[Principal], boolean>,
  'adminDeletePet' : ActorMethod<[string], undefined>,
  'adminGetAllUsers' : ActorMethod<[], Array<[Principal, FullUserProfile]>>,
  'adminGetBannedUsers' : ActorMethod<[], Array<Principal>>,
  'adminGetStats' : ActorMethod<[], Stats>,
  'adminUnbanUser' : ActorMethod<[Principal], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPet' : ActorMethod<[Pet], string>,
  'deletePet' : ActorMethod<[string], undefined>,
  'getAdoptedPets' : ActorMethod<[boolean], Array<Pet>>,
  'getAllPets' : ActorMethod<[], Array<Pet>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [FullUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationParticipants' : ActorMethod<[string], [Principal, Principal]>,
  'getMessages' : ActorMethod<[string], Array<MessageView>>,
  'getMyConversations' : ActorMethod<[], Array<ConversationView>>,
  'getPet' : ActorMethod<[string], [] | [Pet]>,
  'getPetsByLocation' : ActorMethod<[string], Array<Pet>>,
  'getPetsBySpecies' : ActorMethod<[string], Array<Pet>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileResult]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerBanned' : ActorMethod<[], boolean>,
  'markConversationRead' : ActorMethod<[string], undefined>,
  'resetAdminToCaller' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[FullUserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'startOrGetConversation' : ActorMethod<[Principal], string>,
  'updatePet' : ActorMethod<[string, Pet], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];