/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FullUserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const Stats = IDL.Record({
  'totalPets' : IDL.Nat,
  'totalMessages' : IDL.Nat,
  'adoptedPets' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalConversations' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Pet = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Text,
  'photoBlobs' : IDL.Vec(ExternalBlob),
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'size' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'healthStatus' : IDL.Text,
  'breed' : IDL.Text,
  'species' : IDL.Text,
  'location' : IDL.Text,
  'isAdopted' : IDL.Bool,
});
export const Time = IDL.Int;
export const MessageView = IDL.Record({
  'text' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'readBy' : IDL.Vec(IDL.Principal),
});
export const ConversationView = IDL.Record({
  'id' : IDL.Text,
  'messages' : IDL.Vec(MessageView),
  'user1' : IDL.Principal,
  'user2' : IDL.Principal,
});
export const PublicUserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'location' : IDL.Text,
});
export const UserProfileResult = IDL.Variant({
  'publicView' : PublicUserProfile,
  'full' : FullUserProfile,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminGetAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, FullUserProfile))],
      ['query'],
    ),
  'adminGetStats' : IDL.Func([], [Stats], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPet' : IDL.Func([Pet], [IDL.Text], []),
  'deletePet' : IDL.Func([IDL.Text], [], []),
  'getAdoptedPets' : IDL.Func([IDL.Bool], [IDL.Vec(Pet)], ['query']),
  'getAllPets' : IDL.Func([], [IDL.Vec(Pet)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(FullUserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationParticipants' : IDL.Func(
      [IDL.Text],
      [IDL.Principal, IDL.Principal],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(MessageView)], ['query']),
  'getMyConversations' : IDL.Func([], [IDL.Vec(ConversationView)], ['query']),
  'getPet' : IDL.Func([IDL.Text], [IDL.Opt(Pet)], ['query']),
  'getPetsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Pet)], ['query']),
  'getPetsBySpecies' : IDL.Func([IDL.Text], [IDL.Vec(Pet)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileResult)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markConversationRead' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([FullUserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'startOrGetConversation' : IDL.Func([IDL.Principal], [IDL.Text], []),
  'updatePet' : IDL.Func([IDL.Text, Pet], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FullUserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const Stats = IDL.Record({
    'totalPets' : IDL.Nat,
    'totalMessages' : IDL.Nat,
    'adoptedPets' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalConversations' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Pet = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Text,
    'photoBlobs' : IDL.Vec(ExternalBlob),
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'size' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'healthStatus' : IDL.Text,
    'breed' : IDL.Text,
    'species' : IDL.Text,
    'location' : IDL.Text,
    'isAdopted' : IDL.Bool,
  });
  const Time = IDL.Int;
  const MessageView = IDL.Record({
    'text' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'readBy' : IDL.Vec(IDL.Principal),
  });
  const ConversationView = IDL.Record({
    'id' : IDL.Text,
    'messages' : IDL.Vec(MessageView),
    'user1' : IDL.Principal,
    'user2' : IDL.Principal,
  });
  const PublicUserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'location' : IDL.Text,
  });
  const UserProfileResult = IDL.Variant({
    'publicView' : PublicUserProfile,
    'full' : FullUserProfile,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminGetAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, FullUserProfile))],
        ['query'],
      ),
    'adminGetStats' : IDL.Func([], [Stats], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPet' : IDL.Func([Pet], [IDL.Text], []),
    'deletePet' : IDL.Func([IDL.Text], [], []),
    'getAdoptedPets' : IDL.Func([IDL.Bool], [IDL.Vec(Pet)], ['query']),
    'getAllPets' : IDL.Func([], [IDL.Vec(Pet)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(FullUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationParticipants' : IDL.Func(
        [IDL.Text],
        [IDL.Principal, IDL.Principal],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(MessageView)], ['query']),
    'getMyConversations' : IDL.Func([], [IDL.Vec(ConversationView)], ['query']),
    'getPet' : IDL.Func([IDL.Text], [IDL.Opt(Pet)], ['query']),
    'getPetsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Pet)], ['query']),
    'getPetsBySpecies' : IDL.Func([IDL.Text], [IDL.Vec(Pet)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileResult)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markConversationRead' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([FullUserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'startOrGetConversation' : IDL.Func([IDL.Principal], [IDL.Text], []),
    'updatePet' : IDL.Func([IDL.Text, Pet], [], []),
  });
};

export const init = ({ IDL }) => { return []; };